apiVersion: 1

datasources:
  - name: Postgres-SAEB
    uid: postgres-saeb
    type: postgres
    access: proxy
    url: postgres:5432
    database: saeb_faq
    user: saeb_user
    isDefault: true
    editable: true
    secureJsonData:
      password: saeb_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false